version: '3.8'

services:
  apache:
    build: .
    image: php:7.4-apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - topsis_network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-topsis
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - topsis_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - topsis_network

networks:
  topsis_network:
    driver: bridge
